##########################################################
# This is the configuration file for the helpdesk bot.
# Any lines starting with a # are comments and will be ignored.
# Above each key is a description of what that property does,
#   so make sure you read it if you don't know.
# Thank you for your purchase.
##########################################################

# This is the token for your discord bot. It is required.
# You can get it from the Discord Developer Portal @ https://discord.com/developers/applications/.
token: "YOUR DISCORD BOT TOKEN"
# This is the text for the bot's status. You can leave this empty ("") or remove this key in its entirety if you do not want status.
status: "Support"
# This is a list of the IDs of the users who can use the bot.
# You can get a your/any user's ID by enabling developer mode in Discord and right clicking on your/their name.
owners:
  - "810594298021543965"
  - "180280668239036416"
# The ID of the channel where button press logs will be sent.
# Optional - leave empty ("") to disable.
log_channel_id: "810594298021543965"
# The channel & role IDs for support.
assistance_channel_id: "810594298021543965"
assistance_role_id: "810594298021543965"
# Configuration for the embed generated upon running /create.
embed_content:
  # The title of the embed.
  title: "Support Embed Title"
  # The hex code for your embed color.
  color: "00FF00"
  thumbnail:
    # Toggles whether or not the thumbnail is enabled.
    enabled: true
    # The URL of the thumbnail. Required if `enabled` parameter is true.
    url: "https://cdn.discordapp.com/attachments/810594298021543965/810594298021543965/810594298021543965.png"

# A list of questions visible in the helpdesk embed along with their respective responses.
# You can add up to 10.
questions:
  - question: "Question 1"
    response: "Response 1"
  - question: "Question 2"
    response: "Response 2"
